version: '3.7'

version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd dental-site && npm run dev"
    ports:
      - "3030:3000"